### ISSUE TITLE
Add a 'has apt source repo' metadata field to releases (useful for glvd)

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/glrd#1]
**What would you like to be added**:

glrd releases should provide the information if their apt repo provides a source repo. Only releases later than 1592.4 have this.

Not sure what the best way to represent this information would be, for me a 'hasSourceRepo' binary property would be enough, but we might also want to make this a bit more generic, i.e. with links to the source, binary arm, binary amd repo.

When creating new releases in GLRD, this could be inferred from the existing known url schema for apt repos.

**Why is this needed**:

to be used in glvd, the source repo is needed. If we want to use glrd as the universal source of truth for Garden Linux releases, and make applications like glvd use it, it has to provide such filter capabilities. Then the glvd ingestion could query glrd to identify which Garden Linux releases are 'glvd capable', and we could get rid of the hard coded list of versions.

**Comment by yeoldegrove** [comment]
@fwilhe This would look like this ...

Is this sufficient for you?

```

❯ glrd --input-type file --output-format yaml --type patch | tail -58
- type: patch
  version:
    major: 1592
    minor: 3
  lifecycle:
    released:
      isodate: '2024-11-20'
      timestamp: 1732100449
    eol:
      isodate: '2024-12-05'
      timestamp: 1733413070
  name: patch-1592.3
  git:
    commit: f64e280fa763861675f584739d4cfa548fcf8507
    commit_short: f64e280f
  github:
    release: https://github.com/gardenlinux/gardenlinux/releases/tag/1592.3
  attributes:
    source-repo: false
- type: patch
  version:
    major: 1592
    minor: 4
  lifecycle:
    released:
      isodate: '2024-12-05'
      timestamp: 1733413070
    eol:
      isodate: '2025-02-03'
      timestamp: 1738595464
  name: patch-1592.4
  git:
    commit: 00942a0a5c2f25e89651e3f780b913619ffe5212
    commit_short: 00942a0a
  github:
    release: https://github.com/gardenlinux/gardenlinux/releases/tag/1592.4
  attributes:
    source-repo: true
- type: patch
  version:
    major: 1592
    minor: 5
  lifecycle:
    released:
      isodate: '2025-02-03'
      timestamp: 1738595464
    eol:
      isodate: '2025-08-12'
      timestamp: 1754956800
  name: patch-1592.5
  git:
    commit: 0ca92e6b9c816465c2cf42035b73628ac904f455
    commit_short: 0ca92e6b
  github:
    release: https://github.com/gardenlinux/gardenlinux/releases/tag/1592.5
  attributes:
    source-repo: true
```
